# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcf2460a22cc65a77ae3239200a24726fc5b63a589c4dd3bf27c695faf4c98c2494c502879db72749c9899c211c48ac54c578adb2afec9d630f974d76243b8db

test:
  secret_key_base: c71971662181efef4d13eaa92a6b5124e7289fff788c5737002534b37dd92830a4b65fd990a486efe30a97187e7f449f9119f922b2a6dd4bad9a9ce189e6b805

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
